# To Chenery-Moses

This notebook converts the packaged SUT test table to the Chenery-Moses format.

In [1]:
import mario

mario.set_log_verbosity("critical")

In [2]:
sut = mario.load_test("SUT")

## Inspect the starting table

In [3]:
sut.table_type

'SUT'

In [4]:
sut.Z.head()

Region                                Region 1                    Region 2  \
Level                                 Activity                    Activity
Item                             Manufacturing      Services Manufacturing
Region   Level     Item
Region 1 Activity  Manufacturing  0.000000e+00  0.000000e+00  0.000000e+00
                   Services       0.000000e+00  0.000000e+00  0.000000e+00
Region 2 Activity  Manufacturing  0.000000e+00  0.000000e+00  0.000000e+00
                   Services       0.000000e+00  0.000000e+00  0.000000e+00
Region 1 Commodity Goods          3.334903e+11  1.657755e+11  1.487965e+11

Region                                              Region 1                \
Level                                              Commodity
Item                                  Services         Goods      Services
Region   Level     Item
Region 1 Activity  Manufacturing  0.000000e+00  1.240653e+12  3.487923e+10
                   Services       0.000000e+00  7.077650e+10  2.347886e+12
Region 2 Activity  Manufacturing  0.000000e+00  0.000000e+00  0.000000e+00
                   Services       0.000000e+00  0.000000e+00  0.000000e+00
Region 1 Commodity Goods          6.895332e+10  0.000000e+00  0.000000e+00

Region                                Region 2
Level                                Commodity
Item                                     Goods      Services
Region   Level     Item
Region 1 Activity  Manufacturing  0.000000e+00  0.000000e+00
                   Services       0.000000e+00  0.000000e+00
Region 2 Activity  Manufacturing  6.243698e+13  6.506942e+11
                   Services       5.907938e+11  1.039044e+14
Region 1 Commodity Goods          0.000000e+00  0.000000e+00

## Convert the SUT

In [5]:
chenery_moses = sut.to_chenery_moses(inplace=False)
chenery_moses.table_type

'SUT'

## Inspect the converted matrices

In [6]:
chenery_moses.Z.head()

Region                                Region 1                    Region 2  \
Level                                 Activity                    Activity
Item                             Manufacturing      Services Manufacturing
Region   Level     Item
Region 1 Activity  Manufacturing  0.000000e+00  0.000000e+00  0.000000e+00
                   Services       0.000000e+00  0.000000e+00  0.000000e+00
Region 2 Activity  Manufacturing  0.000000e+00  0.000000e+00  0.000000e+00
                   Services       0.000000e+00  0.000000e+00  0.000000e+00
Region 1 Commodity Goods          3.334903e+11  1.657755e+11  1.487965e+11

Region                                              Region 1                \
Level                                              Commodity
Item                                  Services         Goods      Services
Region   Level     Item
Region 1 Activity  Manufacturing  0.000000e+00  1.240653e+12  3.487923e+10
                   Services       0.000000e+00  7.077650e+10  2.347886e+12
Region 2 Activity  Manufacturing  0.000000e+00  0.000000e+00  0.000000e+00
                   Services       0.000000e+00  0.000000e+00  0.000000e+00
Region 1 Commodity Goods          6.895332e+10  0.000000e+00  0.000000e+00

Region                                Region 2
Level                                Commodity
Item                                     Goods      Services
Region   Level     Item
Region 1 Activity  Manufacturing  0.000000e+00  0.000000e+00
                   Services       0.000000e+00  0.000000e+00
Region 2 Activity  Manufacturing  6.243698e+13  6.506942e+11
                   Services       5.907938e+11  1.039044e+14
Region 1 Commodity Goods          0.000000e+00  0.000000e+00

In [7]:
chenery_moses.Y.head()

Region                                       Region 1             Region 2
Level                            Consumption category Consumption category
Item                                     Final demand         Final demand
Region   Level     Item
Region 1 Activity  Manufacturing         0.000000e+00         0.000000e+00
                   Services              0.000000e+00         0.000000e+00
Region 2 Activity  Manufacturing         0.000000e+00         0.000000e+00
                   Services              0.000000e+00         0.000000e+00
Region 1 Commodity Goods                 3.452438e+11         2.491705e+11