# Calculate linkages

This notebook calculates backward and forward linkages from the packaged IOT test table.

In practice, linkages answer two different questions:

- **Backward linkage**: if final demand for one sector increases, how strongly does that sector pull activity from its upstream suppliers? High backward linkage usually points to sectors that mobilize many inputs along the supply chain.
- **Forward linkage**: if output from one sector changes, how strongly does that propagate into downstream sectors that use it as an input? High forward linkage usually points to foundational suppliers, materials, or enabling sectors.

A simple practical reading is often:

- high **backward** = a strong demander of upstream inputs
- high **forward** = a strong provider to downstream sectors
- high **both** = a structurally important node in the production network

MARIO now exposes two extra low-cost diagnostics alongside the standard linkage measures:

- In aggregated mode (``multi_mode=False``), it adds ``Forward Amplification`` and ``Backward Amplification`` ratios computed as ``Total / Direct``.
- In multi-regional mode (``multi_mode=True``), it adds ``Local Share`` and ``Foreign Share`` next to the existing ``Local`` and ``Foreign`` linkage components.

In [1]:
import mario

mario.set_log_verbosity("critical")

In [2]:
db = mario.load_test("IOT")

## Calculate standard linkages

In [3]:
linkages = db.calc_linkages()
linkages

                          Total Forward           Total Backward            \
                                  Local   Foreign          Local   Foreign
Region Level  Item
Reg1   Sector Agriculture      1.666294  0.018902       0.677298  0.004176
              Industry         0.603459  0.011319       0.769900  0.011625
              Services         0.316985  0.004014       0.326764  0.004308
Reg2   Sector Agriculture      0.831638  0.358655       0.588834  0.254638
              Industry         0.278985  0.554928       0.559941  0.625173
              Services         0.270668  0.172430       0.139792  0.182449

                          Direct Forward           Direct Backward            \
                                   Local   Foreign           Local   Foreign
Region Level  Item
Reg1   Sector Agriculture       0.645103  0.006349        0.302440  0.000892
              Industry          0.221656  0.003138        0.284198  0.002855
              Services          0.111307  0.000839        0.112218  0.001003
Reg2   Sector Agriculture       0.483367  0.048290        0.330838  0.063600
              Industry          0.142901  0.172260        0.286858  0.178419
              Services          0.136041  0.022979        0.069910  0.041029

                          Total Forward               Total Backward  \
                            Local Share Foreign Share    Local Share
Region Level  Item
Reg1   Sector Agriculture      0.988783      0.011217       0.993873
              Industry         0.981588      0.018412       0.985126
              Services         0.987496      0.012504       0.986989
Reg2   Sector Agriculture      0.698684      0.301316       0.698107
              Industry         0.334549      0.665451       0.472478
              Services         0.610853      0.389147       0.433811

                                        Direct Forward                \
                          Foreign Share    Local Share Foreign Share
Region Level  Item
Reg1   Sector Agriculture      0.006127       0.990254      0.009746
              Industry         0.014874       0.986039      0.013961
              Services         0.013011       0.992521      0.007479
Reg2   Sector Agriculture      0.301893       0.909171      0.090829
              Industry         0.527522       0.453421      0.546579
              Services         0.566189       0.855498      0.144502

                          Direct Backward
                              Local Share Foreign Share
Region Level  Item
Reg1   Sector Agriculture        0.997058      0.002942
              Industry           0.990053      0.009947
              Services           0.991139      0.008861
Reg2   Sector Agriculture        0.838757      0.161243
              Industry           0.616532      0.383468
              Services           0.630168      0.369832

The default multi-regional output keeps the absolute ``Local`` and ``Foreign`` components for each linkage and now also reports their shares. This makes it easier to distinguish the size of a linkage from its domestic-versus-external composition.

A practical way to read the columns is:

- ``Direct``: the first-round effect only
- ``Total``: direct plus all indirect rounds through the production network
- ``Local`` / ``Foreign``: where that linkage is geographically activated
- ``Local Share`` / ``Foreign Share``: how the linkage is split, regardless of absolute size

So two sectors can have the same total linkage but very different supply-chain geography: one mostly domestic, the other heavily dependent on foreign production chains.

## Calculate aggregated linkages and amplification ratios

In [4]:
aggregated_linkages = db.calc_linkages(multi_mode=False)
aggregated_linkages

                           Total Forward  Total Backward  Direct Forward  \
Region Level  Item
Reg1   Sector Agriculture       1.987151        0.986476        1.960012
              Industry          0.724935        1.131306        0.676333
              Services          0.378516        0.479247        0.337412
Reg2   Sector Agriculture       1.403570        1.220979        1.599585
              Industry          0.983334        1.715527        0.948219
              Services          0.522493        0.466464        0.478438

                           Direct Backward  Forward Amplification  \
Region Level  Item
Reg1   Sector Agriculture         1.087044               2.586831
              Industry            1.028705               2.734854
              Services            0.405748               2.862325
Reg2   Sector Agriculture         1.413536               2.238837
              Industry            1.667399               2.645992
              Services            0.397568               2.786448

                           Backward Amplification
Region Level  Item
Reg1   Sector Agriculture                2.246626
              Industry                   2.722578
              Services                   2.924115
Reg2   Sector Agriculture                2.138416
              Industry                   2.547119
              Services                   2.904678

``Forward Amplification`` and ``Backward Amplification`` are computed as ``Total / Direct``. Values above 1 indicate that indirect supply-chain effects amplify the direct linkage.

In practical terms, a sector with a modest direct linkage but a high amplification ratio is one where the first-round effect looks limited, yet the wider chain reaction through suppliers or users is much larger. This is often the interesting case when you want to identify hidden systemic importance rather than only the obvious first-tier effect.

## Calculate non-normalized linkages

In [6]:
db.calc_linkages(normalized=False)

                          Total Forward           Total Backward            \
                                  Local   Foreign          Local   Foreign
Region Level  Item
Reg1   Sector Agriculture      1.666294  0.018902       0.677298  0.004176
              Industry         0.603459  0.011319       0.769900  0.011625
              Services         0.316985  0.004014       0.326764  0.004308
Reg2   Sector Agriculture      0.831638  0.358655       0.588834  0.254638
              Industry         0.278985  0.554928       0.559941  0.625173
              Services         0.270668  0.172430       0.139792  0.182449

                          Direct Forward           Direct Backward            \
                                   Local   Foreign           Local   Foreign
Region Level  Item
Reg1   Sector Agriculture       0.645103  0.006349        0.302440  0.000892
              Industry          0.221656  0.003138        0.284198  0.002855
              Services          0.111307  0.000839        0.112218  0.001003
Reg2   Sector Agriculture       0.483367  0.048290        0.330838  0.063600
              Industry          0.142901  0.172260        0.286858  0.178419
              Services          0.136041  0.022979        0.069910  0.041029

                          Total Forward               Total Backward  \
                            Local Share Foreign Share    Local Share
Region Level  Item
Reg1   Sector Agriculture      0.988783      0.011217       0.993873
              Industry         0.981588      0.018412       0.985126
              Services         0.987496      0.012504       0.986989
Reg2   Sector Agriculture      0.698684      0.301316       0.698107
              Industry         0.334549      0.665451       0.472478
              Services         0.610853      0.389147       0.433811

                                        Direct Forward                \
                          Foreign Share    Local Share Foreign Share
Region Level  Item
Reg1   Sector Agriculture      0.006127       0.990254      0.009746
              Industry         0.014874       0.986039      0.013961
              Services         0.013011       0.992521      0.007479
Reg2   Sector Agriculture      0.301893       0.909171      0.090829
              Industry         0.527522       0.453421      0.546579
              Services         0.566189       0.855498      0.144502

                          Direct Backward
                              Local Share Foreign Share
Region Level  Item
Reg1   Sector Agriculture        0.997058      0.002942
              Industry           0.990053      0.009947
              Services           0.991139      0.008861
Reg2   Sector Agriculture        0.838757      0.161243
              Industry           0.616532      0.383468
              Services           0.630168      0.369832

With ``normalized=False``, MARIO returns raw linkage magnitudes instead of relative scores around the system average.

Use the normalized view when the goal is comparison across sectors. Use the non-normalized view when you care about absolute magnitude and want to preserve scale instead of asking whether a sector is above or below average.

## Keep diagonal terms in the calculation

In [7]:
db.calc_linkages(cut_diag=False)

                          Total Forward           Total Backward            \
                                  Local   Foreign          Local   Foreign
Region Level  Item
Reg1   Sector Agriculture      2.806501  0.018902       1.817505  0.004176
              Industry         2.504475  0.011319       2.670916  0.011625
              Services         1.816343  0.004014       1.826122  0.004308
Reg2   Sector Agriculture      1.876879  0.358655       1.634075  0.254638
              Industry         1.648511  0.554928       1.929467  0.625173
              Services         1.747789  0.172430       1.616912  0.182449

                          Direct Forward           Direct Backward            \
                                   Local   Foreign           Local   Foreign
Region Level  Item
Reg1   Sector Agriculture       0.738449  0.006349        0.395786  0.000892
              Industry          0.652657  0.003138        0.715199  0.002855
              Services          0.404123  0.000839        0.405034  0.001003
Reg2   Sector Agriculture       0.520469  0.048290        0.367939  0.063600
              Industry          0.383182  0.172260        0.527139  0.178419
              Services          0.434589  0.022979        0.368459  0.041029

                          Total Forward               Total Backward  \
                            Local Share Foreign Share    Local Share
Region Level  Item
Reg1   Sector Agriculture      0.993310      0.006690       0.997708
              Industry         0.995501      0.004499       0.995667
              Services         0.997795      0.002205       0.997647
Reg2   Sector Agriculture      0.839566      0.160434       0.865179
              Industry         0.748154      0.251846       0.755279
              Services         0.910203      0.089797       0.898603

                                        Direct Forward                \
                          Foreign Share    Local Share Foreign Share
Region Level  Item
Reg1   Sector Agriculture      0.002292       0.991476      0.008524
              Industry         0.004333       0.995215      0.004785
              Services         0.002353       0.997929      0.002071
Reg2   Sector Agriculture      0.134821       0.915096      0.084904
              Industry         0.244721       0.689869      0.310131
              Services         0.101397       0.949781      0.050219

                          Direct Backward
                              Local Share Foreign Share
Region Level  Item
Reg1   Sector Agriculture        0.997751      0.002249
              Industry           0.996023      0.003977
              Services           0.997529      0.002471
Reg2   Sector Agriculture        0.852620      0.147380
              Industry           0.747124      0.252876
              Services           0.899805      0.100195