# Calculate linkages

This notebook calculates backward and forward linkages from the packaged IOT test table.

In [1]:
import mario

mario.set_log_verbosity("critical")

In [2]:
db = mario.load_test("IOT")

## Calculate standard linkages

In [3]:
linkages = db.calc_linkages()
linkages

                          Total Forward           Total Backward            \
                                  Local   Foreign          Local   Foreign
Region Level  Item
Reg1   Sector Agriculture      1.666294  0.018902       0.677298  0.004176
              Industry         0.603459  0.011319       0.769900  0.011625
              Services         0.316985  0.004014       0.326764  0.004308
Reg2   Sector Agriculture      0.831638  0.358655       0.588834  0.254638
              Industry         0.278985  0.554928       0.559941  0.625173
              Services         0.270668  0.172430       0.139792  0.182449

                          Direct Forward           Direct Backward
                                   Local   Foreign           Local   Foreign
Region Level  Item
Reg1   Sector Agriculture       0.645103  0.006349        0.302440  0.000892
              Industry          0.221656  0.003138        0.284198  0.002855
              Services          0.111307  0.000839        0.112218  0.001003
Reg2   Sector Agriculture       0.483367  0.048290        0.330838  0.063600
              Industry          0.142901  0.172260        0.286858  0.178419
              Services          0.136041  0.022979        0.069910  0.041029

## Calculate non-normalized linkages

In [4]:
db.calc_linkages(normalized=False)

                          Total Forward           Total Backward            \
                                  Local   Foreign          Local   Foreign
Region Level  Item
Reg1   Sector Agriculture      1.666294  0.018902       0.677298  0.004176
              Industry         0.603459  0.011319       0.769900  0.011625
              Services         0.316985  0.004014       0.326764  0.004308
Reg2   Sector Agriculture      0.831638  0.358655       0.588834  0.254638
              Industry         0.278985  0.554928       0.559941  0.625173
              Services         0.270668  0.172430       0.139792  0.182449

                          Direct Forward           Direct Backward
                                   Local   Foreign           Local   Foreign
Region Level  Item
Reg1   Sector Agriculture       0.645103  0.006349        0.302440  0.000892
              Industry          0.221656  0.003138        0.284198  0.002855
              Services          0.111307  0.000839        0.112218  0.001003
Reg2   Sector Agriculture       0.483367  0.048290        0.330838  0.063600
              Industry          0.142901  0.172260        0.286858  0.178419
              Services          0.136041  0.022979        0.069910  0.041029

## Keep diagonal terms in the calculation

In [5]:
db.calc_linkages(cut_diag=False)

                          Total Forward           Total Backward            \
                                  Local   Foreign          Local   Foreign
Region Level  Item
Reg1   Sector Agriculture      2.806501  0.018902       1.817505  0.004176
              Industry         2.504475  0.011319       2.670916  0.011625
              Services         1.816343  0.004014       1.826122  0.004308
Reg2   Sector Agriculture      1.876879  0.358655       1.634075  0.254638
              Industry         1.648511  0.554928       1.929467  0.625173
              Services         1.747789  0.172430       1.616912  0.182449

                          Direct Forward           Direct Backward
                                   Local   Foreign           Local   Foreign
Region Level  Item
Reg1   Sector Agriculture       0.738449  0.006349        0.395786  0.000892
              Industry          0.652657  0.003138        0.715199  0.002855
              Services          0.404123  0.000839        0.405034  0.001003
Reg2   Sector Agriculture       0.520469  0.048290        0.367939  0.063600
              Industry          0.383182  0.172260        0.527139  0.178419
              Services          0.434589  0.022979        0.368459  0.041029