# Shock analyses

This workflow covers the standard way to apply a shock to a *database* by creating a new scenario via the dedicate Excel template.

Core methods
------------

The two main entry points are:

* `Database.get_shock_excel` to write the workbook template;
* `Database.shock_calc` to read that workbook and store a shocked scenario.

Typical flow
------------

The usual sequence is:

* generate a template workbook from the current database
* fill the rows you want to shock
* apply the workbook into a named scenario

___
## Apply shocks to IOTs

Load the test IOT table embedded into MARIO

In [ ]:
import mario
db_IOT = mario.load_test("IOT")

INFO Parser: excel reading IOT flows from /Users/lorenzorinaldi/Documents/GitHub/MARIO/mario/test/tables/test_IOT_standard.xlsx.
INFO Parser: state payload ready with 6 canonical blocks.
INFO Parser: excel state ready for IOT.
INFO Metadata: initialized.

## Generate an empty shock template

In [ ]:
db_IOT.get_shock_excel(
    path="/path/to/shock_IOT_template.xlsx",
)

## Fill shock template

Fill the shocked template to simulate a change in consumption of "Industry" outputs from both "Reg1" and "Reg2" by "Services" sector in "Reg2", which would cause also an increase in CO2 emissions of such sector. 

These changes affect only `z` and `e` matrices

Being a simplified example, only "Percentage" change type are adopted, but also "Absolute" and "Update" changes could be used

![shock_iot_template](../../_static/images/shock_IOT_template.png)

## Apply a filled shock workbook

For IOTs, the matrices that can be shocked are ``z``, ``v``, ``e`` and ``Y``.

In our example, the filled workbook updates one `z` and `e` coefficient matrices. We use the ``scenario`` argument to define the output name of the new scenario. If omitted, MARIO creates a name such as ``shock 1`` automatically.

### Download the packaged example workbooks

The exact workbooks used in this notebook are available here:

- [IOT shock template](../../_static/data/supporting_files/shock_IOT_template.xlsx)
- [Filled IOT shock workbook](../../_static/data/supporting_files/shock_IOT_filled.xlsx)
- [SUT shock template](../../_static/data/supporting_files/shock_SUT_template.xlsx)
- [Filled SUT shock workbook](../../_static/data/supporting_files/shock_SUT_filled.xlsx)
- [IOT cluster shock template](../../_static/data/supporting_files/shock_IOT_template_clusters.xlsx)
- [Filled IOT cluster shock workbook](../../_static/data/supporting_files/shock_IOT_filled_clusters.xlsx)

In [ ]:
db_IOT.shock_calc(
    io="/path/to/shock_IOT_filled.xlsx",
    z=True,
    e=True,
    scenario="example shock",
)

INFO Resolver: resolving z for baseline.

INFO Resolver: trying z via formula build_iot_z_from_Z_X.

INFO Resolver: resolved z via formula build_iot_z_from_Z_X.

INFO Resolver: resolving e for baseline.

INFO Resolver: trying e via formula build_iot_e_from_E_X.

INFO Resolver: resolved e via formula build_iot_e_from_E_X.

INFO Resolver: resolving v for baseline.

INFO Resolver: trying v via formula build_iot_v_from_V_X.

INFO Resolver: resolved v via formula build_iot_v_from_V_X.

INFO Shock: Shock implemented successfully.

You will notice the *database* now has 2 scenarios

In [4]:
db_IOT.scenarios

['baseline', 'example shock']

## Inspect the shocked coefficient matrix

The `query` method can also be used to check variations (absolute or relative) of matrices across scenarios.

In [5]:
db_IOT.query(
    matrices="z", 
    scenarios="example shock", 
    base_scenario="baseline", 
    type="relative"
)

Region                           Reg1                          Reg2           \
Level                          Sector                        Sector
Item                      Agriculture Industry Services Agriculture Industry
Region Level  Item
Reg1   Sector Agriculture         0.0      0.0      0.0         0.0      0.0
              Industry            0.0      0.0      0.0         0.0      0.0
              Services            0.0      0.0      0.0         0.0      0.0
Reg2   Sector Agriculture         0.0      0.0      0.0         0.0      0.0
              Industry            0.0      0.0      0.0         0.0      0.0
              Services            0.0      0.0      0.0         0.0      0.0

Region
Level
Item                      Services
Region Level  Item
Reg1   Sector Agriculture      0.0
              Industry         0.2
              Services         0.0
Reg2   Sector Agriculture      0.0
              Industry         0.3
              Services         0.0

___
## Apply shocks to SUTs

Load the test SUT table embedded into MARIO

In [3]:
import mario
db_SUT = mario.load_test("SUT")

INFO Parser: excel reading SUT flows from /Users/lorenzorinaldi/Documents/GitHub/MARIO/mario/test/tables/test_SUT_standard.xlsx.
INFO Parser: state payload ready with 10 canonical blocks.
INFO Parser: excel state ready for SUT.
INFO Metadata: initialized.

## Generate an empty shock template

In [ ]:
db_SUT.get_shock_excel(
    path="/path/to/shock_SUT_template.xlsx",
)

INFO Resolver: resolving u for baseline.

INFO Resolver: trying u via extract.

INFO Resolver: trying u via formula build_sut_u_from_U_Xa.

INFO Resolver: resolved u via formula build_sut_u_from_U_Xa.

INFO Resolver: resolving s for baseline.

INFO Resolver: trying s via extract.

INFO Resolver: trying s via formula build_sut_s_from_S_Xc.

INFO Resolver: resolved s via formula build_sut_s_from_S_Xc.

INFO Resolver: resolving va for baseline.

INFO Resolver: trying va via formula build_sut_va_from_Va_Xa.

INFO Resolver: resolved va via formula build_sut_va_from_Va_Xa.

INFO Resolver: resolving vc for baseline.

INFO Resolver: trying vc via formula build_sut_vc_from_Vc_Xc.

INFO Resolver: resolved vc via formula build_sut_vc_from_Vc_Xc.

INFO Resolver: resolving ea for baseline.

INFO Resolver: trying ea via formula build_sut_ea_from_Ea_Xa.

INFO Resolver: resolved ea via formula build_sut_ea_from_Ea_Xa.

INFO Resolver: resolving ec for baseline.

INFO Resolver: trying ec via formula build_sut_ec_from_Ec_Xc.

INFO Resolver: resolved ec via formula build_sut_ec_from_Ec_Xc.

## Fill shock template

To simulate a similar shock with respect to the IOT case, fill the shock template to simulate a change in consumption of "Goods" outputs from both "Region 1" and "Region 2" by "Services" activity in "Region 2", which would cause also an increase in CO2 emissions of such sector. 

These changes affect now the `u` (instead of `z`) and `ea` (instead of `e`) matrices.

Again, only "Percentage" change type are adopted.

![shock_sut_template](../../_static/images/shock_SUT_template.png)

## Apply a filled shock workbook

For SUTs, the matrices that can be shocked are:

* ``u`` and ``s`` instead of ``z``
* ``va`` and ``vc`` instead of ``v``
* ``ea`` and ``ec`` instead of ``e``
* ``Ya`` and ``Yc`` instead of ``Y``

In our example, the filled workbook updates one `u` and `ea` coefficient matrices. 

N.B. The template workbook will only generate non-fully empty matrices (e.g. in this example ``ec`` is fully empty)

In [ ]:
db_SUT.shock_calc(
    io="/path/to/shock_SUT_filled.xlsx",
    z=True,
    e=True,
    scenario="example shock",
)

NameError: name 'db_SUT' is not defined

In [9]:
db_SUT.scenarios

['baseline', 'example shock']

## Inspect the shocked coefficient matrix

Use again the `query` method

In [10]:
db_SUT.query(
    matrices="u", 
    scenarios="example shock", 
    base_scenario="baseline", 
    type="relative"
)

INFO Resolver: resolving u for example shock.

INFO Resolver: trying u via extract.

INFO Resolver: resolved u via extract.

Region                           Region 1               Region 2
Level                            Activity               Activity
Item                        Manufacturing Services Manufacturing Services
Region   Level     Item
Region 1 Commodity Goods              0.0      0.0           0.0      0.2
                   Services           0.0      0.0           0.0      0.0
Region 2 Commodity Goods              0.0      0.0           0.0      0.3
                   Services           0.0      0.0           0.0      0.0

___
## Clusters

Shock templates and shock application both understand clusters.

You can:

* rely on default clusters already available on the database (e.g. "all" for *Regions*)
* store reusable custom clusters on the database
* pass ad hoc clusters directly to ``get_shock_excel(...)`` or ``shock_calc(...)``

This is useful when a single workbook row should target multiple regions,
sectors, activities, commodities, or final-demand categories at once.

In [11]:
clusters = {
    'Sector': {
        'Agr_Serv': ['Agriculture', 'Services']
    }
}

In [ ]:
db_IOT.get_shock_excel(
    path="/path/to/shock_IOT_template_clusters.xlsx",
    clusters=clusters
)

When passing the ``clusters`` argument, you will see the clusters are allowed to be selected.  

![shock_iot_clusters](../../_static/images/shock_IOT_clusters.png)

Then with the ``shock_calc`` method, you can parse the template back.

In [ ]:
db_IOT.shock_calc(
    io="/path/to/shock_IOT_filled_clusters.xlsx",
    z=True,
    e=True,
    scenario="example shock clusters",
    clusters=clusters
)

INFO Shock: Shock implemented successfully.

In [14]:
db_IOT.query(
    matrices="z", 
    scenarios="example shock clusters", 
    base_scenario="example shock", 
    type="relative"
)

Region                           Reg1                          Reg2           \
Level                          Sector                        Sector
Item                      Agriculture Industry Services Agriculture Industry
Region Level  Item
Reg1   Sector Agriculture         0.0      0.0      0.0         0.0      0.0
              Industry            0.0      0.0      0.0         0.0      0.0
              Services            0.0      0.0      0.0         0.0      0.0
Reg2   Sector Agriculture         0.0      0.0      0.0         0.0      0.0
              Industry            0.0      0.0      0.0         0.0      0.0
              Services            0.0      0.0      0.0         0.0      0.0

Region
Level
Item                      Services
Region Level  Item
Reg1   Sector Agriculture     0.05
              Industry        0.00
              Services        0.05
Reg2   Sector Agriculture     0.05
              Industry        0.00
              Services        0.05