# To Chenery-Moses

This notebook converts the packaged SUT test table to the Chenery-Moses format.


## Core method

The relevant entry point is `Database.to_chenery_moses`.


## What changes

This transformation changes the international trade modelling assumption underlying the database

* Isard model: goods are differentiated by place of origin (R1 or R2). Each demand flow (intermediate or final) is explicitly allocated across distinct regional or foreign suppliers. The SUT therefore records who supplies whom, keeping trade flows separated by origin. This yields a detailed representation of trade without assuming perfect substitutability between sources.

* Chenery-Moses model: In the Chenery–Moses approach, goods are treated as homogeneous regardless of origin. Total supply (domestic + imports) is pooled and then allocated to uses (intermediate and final demand) using average import shares. The supplying origin is no longer tracked for each use; instead, a common domestic/import proportion is applied across all demand, simplifying the trade structure.

Updates the relevant SUT matrices for the selected scenarios and then resets those scenarios to flow matrices so coefficient-side matrices can be rebuilt consistently on demand.

![chenery-moses](../../_static/images/Chenery-Moses.png)

In [1]:
import mario

In [2]:
isard_sut = mario.load_test("SUT")

INFO Parser: excel reading SUT flows from /path/to/MARIO/mario/test/new/test_SUT_standard.xlsx.

INFO Parser: state payload ready with 10 canonical blocks.

INFO Parser: excel state ready for SUT.

INFO Metadata: initialized.

## Inspect the starting table

In [3]:
isard_sut.table_type

'SUT'

In [4]:
isard_sut.U

Region                           Region 1                    Region 2  \
Level                            Activity                    Activity
Item                        Manufacturing      Services Manufacturing
Region   Level     Item
Region 1 Commodity Goods     3.334903e+11  1.657755e+11  1.487965e+11
                   Services  3.261811e+11  7.254021e+11  1.176727e+10
Region 2 Commodity Goods     1.922623e+11  4.099986e+10  3.038628e+13
                   Services  2.614852e+10  5.823465e+10  1.154871e+13

Region
Level
Item                             Services
Region   Level     Item
Region 1 Commodity Goods     6.895332e+10
                   Services  3.588505e+10
Region 2 Commodity Goods     1.157115e+13
                   Services  3.075294e+13

In [5]:
isard_sut.S

Region                               Region 1                    Region 2  \
Level                               Commodity                   Commodity
Item                                    Goods      Services         Goods
Region   Level    Item
Region 1 Activity Manufacturing  1.240653e+12  3.487923e+10  0.000000e+00
                  Services       7.077650e+10  2.347886e+12  0.000000e+00
Region 2 Activity Manufacturing  0.000000e+00  0.000000e+00  6.243698e+13
                  Services       0.000000e+00  0.000000e+00  5.907938e+11

Region
Level
Item                                 Services
Region   Level    Item
Region 1 Activity Manufacturing  0.000000e+00
                  Services       0.000000e+00
Region 2 Activity Manufacturing  6.506942e+11
                  Services       1.039044e+14

In [6]:
isard_sut.is_isard()

INFO Resolver: resolving Z for baseline.

INFO Resolver: trying Z via concat.

INFO Resolver: resolved Z via concat.

INFO Test: table is in Isard format

True

## Convert the SUT

In [7]:
chenery_moses_sut = isard_sut.to_chenery_moses(inplace=False)

INFO Test: table is not in Chenery-Moses format

INFO Database: Transforming the database into Chenery-Moses

INFO Resolver: resolving Y for baseline.

INFO Resolver: trying Y via concat.

INFO Resolver: resolved Y via concat.

INFO Resolver: resolving s for baseline.

INFO Resolver: trying s via extract.

INFO Resolver: trying s via formula build_sut_s_from_S_Xc.

INFO Resolver: resolved s via formula build_sut_s_from_S_Xc.

INFO Databases: reset to flows.

INFO Transformation of the database from into Chenery-Moses

In [8]:
chenery_moses_sut.U

Region                           Region 1                    Region 2  \
Level                            Activity                    Activity
Item                        Manufacturing      Services Manufacturing
Region   Level     Item
Region 1 Commodity Goods     3.334903e+11  1.657755e+11  1.487965e+11
                   Services  3.261811e+11  7.254021e+11  1.176727e+10
Region 2 Commodity Goods     1.922623e+11  4.099986e+10  3.038628e+13
                   Services  2.614852e+10  5.823465e+10  1.154871e+13

Region
Level
Item                             Services
Region   Level     Item
Region 1 Commodity Goods     6.895332e+10
                   Services  3.588505e+10
Region 2 Commodity Goods     1.157115e+13
                   Services  3.075294e+13

In [9]:
chenery_moses_sut.S

Region                               Region 1                    Region 2  \
Level                               Commodity                   Commodity
Item                                    Goods      Services         Goods
Region   Level    Item
Region 1 Activity Manufacturing  1.240653e+12  3.487923e+10  0.000000e+00
                  Services       7.077650e+10  2.347886e+12  0.000000e+00
Region 2 Activity Manufacturing  0.000000e+00  0.000000e+00  6.243698e+13
                  Services       0.000000e+00  0.000000e+00  5.907938e+11

Region
Level
Item                                 Services
Region   Level    Item
Region 1 Activity Manufacturing  0.000000e+00
                  Services       0.000000e+00
Region 2 Activity Manufacturing  6.506942e+11
                  Services       1.039044e+14